name       : mercurial
version    : 5.9.3
release    : 39
source     :
    - https://www.mercurial-scm.org/release/mercurial-5.9.3.tar.gz : 3b43f68977ad0fa75aa7f1e5c8f0a83ba935621ab2396129abb498e56d1be08e
license    : GPL-2.0-or-later
summary    : Mercurial is a free, distributed source control management tool.
component  : programming.tools
description: |
    Mercurial is a free, distributed source control management tool. It efficiently handles projects of any size and offers an easy and intuitive interface.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
    # Docs
    install -d $installdir/usr/share/man/{man1,man5}
    install -m00644 doc/hg.1 $installdir/usr/share/man/man1
    install -m00644 doc/{hgrc.5,hgignore.5} $installdir/usr/share/man/man5
    install -m00755 contrib/hgk $installdir/usr/bin
    # Completions
    install -Dm00644 contrib/zsh_completion $installdir/usr/share/zsh/site-functions/_hg
    install -Dm00644 contrib/bash_completion $installdir/usr/share/bash-completion/completions/hg
    install -d $installdir/usr/share/emacs/site-lisp
    install -m00644 contrib/{mq.el,mercurial.el} $installdir/usr/share/emacs/site-lisp
    install -Dm00644 contrib/vim/HGAnnotate.vim $installdir/usr/share/vim/vimfiles/syntax/HGAnnotate.vim
#check      : |
#    TESTFLAGS="%JOBS% --tmpdir tmp --blacklist blacklists/failed-tests" \
#    make check
