name       : mercurial
version    : 4.7.2
release    : 34
source     :
    - https://www.mercurial-scm.org/release/mercurial-4.7.2.tar.gz : 97f0594216f2348a2e37b2ad8a56eade044e741153fee8c584487e9934ca09fb
license    : GPL-2.0-or-later
summary    : Mercurial is a free, distributed source control management tool.
component  : programming.tools
description: |
    Mercurial is a free, distributed source control management tool. It efficiently handles projects of any size and offers an easy and intuitive interface.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
    # Docs
    install -d $installdir/usr/share/man/{man1,man5}
    install -m00644 doc/hg.1 $installdir/usr/share/man/man1
    install -m00644 doc/{hgrc.5,hgignore.5} $installdir/usr/share/man/man5
    install -m00755 contrib/hgk $installdir/usr/bin
    # Completions
    install -m00644 -D contrib/zsh_completion $installdir/usr/share/zsh/site-functions/_hg
    install -m00644 -D contrib/bash_completion $installdir/usr/share/bash-completion/completions/hg
    install -d $installdir/usr/share/emacs/site-lisp
    install -m00644 contrib/{mq.el,mercurial.el} $installdir/usr/share/emacs/site-lisp
    install -Dm00644 contrib/vim/HGAnnotate.vim $installdir/usr/share/vim/vimfiles/syntax/HGAnnotate.vim
    ## fix for tortoisehg
    rm -rf $installdir/usr/lib/python2.7/site-packages/hgext3rd
#check      : |
#    TESTFLAGS="%JOBS% --tmpdir tmp --blacklist blacklists/failed-tests" \
#    make check
