name       : mercurial
version    : '4.3'
release    : 23
source     :
    - https://www.mercurial-scm.org/release/mercurial-4.3.tar.gz : ebf11176e9b5354ec7a1bde6c5382c914d10c397410531faf89f8b5124a7cb65
license    : GPL-2.0
summary    : Mercurial is a free, distributed source control management tool.
component  : programming.tools
description: |
    Mercurial is a free, distributed source control management tool. It efficiently handles projects of any size and offers an easy and intuitive interface.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
    # Docs
    install -d $installdir/usr/share/man/{man1,man5}
    install -m644 doc/hg.1 $installdir/usr/share/man/man1
    install -m644 doc/{hgrc.5,hgignore.5} $installdir/usr/share/man/man5
    install -m755 contrib/hgk $installdir/usr/bin
    # Completions
    install -m644 -D contrib/zsh_completion $installdir/usr/share/zsh/site-functions/_hg
    install -m644 -D contrib/bash_completion $installdir/usr/share/bash-completion/completions/hg
    install -d $installdir/usr/share/emacs/site-lisp
    install -m644 contrib/{mq.el,mercurial.el} $installdir/usr/share/emacs/site-lisp
    install -Dm644 contrib/vim/HGAnnotate.vim $installdir/usr/share/vim/vimfiles/syntax/HGAnnotate.vim
